### PR TITLE
HOTT-1596: Remove unused goods nomenclature entities

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

https://transformuk.atlassian.net/browse/HOTT-1596

### What?

I have added/removed/altered:

- [x] Removed unused imports
- [ ] ~~Added support for removing missing goods nomenclature related resources (especially indents/description periods)~~

### Why?

I am doing this because:

- ~~This is required as part of an ongoing battle to comprehend the different types of import approach that are required by DIT/CDS~~
- We're not planning/do not have any intention on ever using the goods nomenclature historical hierarchy functionality

### Out of scope

- I'm not changing/dropping the existing data for now. This can come later

### CODE REVIEW

**Comment by willfish** [comment]
I'll update the mapper to use our missing entity DSL in a separate PR

**Comment by willfish** [comment]
There's actually quite rich information around origin/successor entities that we could potentially use to augment/redirect/improve navigation around missing commodities/goods nomenclature

**Comment by willfish** [comment]
Going to leave unmerged for now

**Comment by willfish** [comment]
After discussing with the team, I'm going to remove the group stuff but not successor/origin

**Review by jebw — APPROVED** [review]
LGTM

**Pull request merged**
