### PR TITLE
OTT-248: Increase section title limit

### PR DESCRIPTION
**Pull request by maverickvi**
### Jira link

https://transformuk.atlassian.net/browse/OTT-248

### What?

I have added/removed/altered:

- [ ] Increase section title limit

### Why?

I am doing this because:

- We need to update a title that is more than 255 characters in length

### Deployment risks (optional)

- Includes destructive/migratory actions which may effect critical data

### CODE REVIEW

**Review by HWallenberg — DISMISSED** [review]

**Review by jebw — CHANGES_REQUESTED** [review]
This works but it might be nicer to use the migrations own DSL rather than raw SQL?

https://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-alter_table

More significantly this does not record the changes to `structure.sql`

**Comment by maverickvi** [comment]
@jebw changes added to structure.sql. I'm skipping the nicer DSL change as I have already tested the raw version and the result would be the same so would like to save some time

**Review by willfish — APPROVED** [review]
Small preference for changing the type to TEXT (assuming this is easier) but otherwise this looks great to me

**Review by jebw — APPROVED** [review]
LGTM

**Pull request merged**
