### PR TITLE
GL-364: Add model for exemption overrides, possibly should 'relate' to certificates model

### PR DESCRIPTION
**Pull request by rasikasri**
### Jira link

[GL-364](https://transformuk.atlassian.net/browse/GL-364)

### What?

I have added/removed/altered:

- [ ] Added GreenLane::ExemptingCertificateOverride model
- [ ] Associate it with Certificate model

### Why?

I am doing this because:

- This model represents certificates that included exemption or excluded exemption, exception to its default behaviour

### CODE REVIEW

**Review by jebw — CHANGES_REQUESTED** [review]
Looks good but can you add a relationship back from the certificate to the override class

When this is getting loaded in it'll be chaining through from the certificate to the override rather than vice versa

**Comment by rasikasri** [comment]
> Looks good but can you add a relationship back from the certificate to the override class
> 
> When this is getting loaded in it'll be chaining through from the certificate to the override rather than vice versa

I added the relationship now

**Review by jebw — DISMISSED** [review]
LGTM

**Review by alexdesi — APPROVED** [review]
:white_check_mark:

**Pull request merged**
